C     I1MACH - INTEGER MACHINE CONSTANTS FOR IBM 360/370
C     CONFIGURED FOR IBM SYSTEM/360 FORTRAN G
C
      INTEGER FUNCTION I1MACH (I)
C
C     MACHINE CONSTANTS FOR THE IBM 360/370 SERIES,
C     THE XEROX SIGMA 5/7/9, THE SEL SYSTEMS 85/86, AND
C     THE PERKIN ELMER (INTERDATA) 7/32.
C
      INTEGER IMACH(16)
C
      DATA IMACH( 1) /          5 /
      DATA IMACH( 2) /          6 /
      DATA IMACH( 3) /          7 /
      DATA IMACH( 4) /          6 /
      DATA IMACH( 5) /         32 /
      DATA IMACH( 6) /          4 /
      DATA IMACH( 7) /          2 /
      DATA IMACH( 8) /         31 /
      DATA IMACH( 9) /  2147483647 /
      DATA IMACH(10) /         16 /
      DATA IMACH(11) /          6 /
      DATA IMACH(12) /        -64 /
      DATA IMACH(13) /         63 /
      DATA IMACH(14) /         14 /
      DATA IMACH(15) /        -64 /
      DATA IMACH(16) /         63 /
C
C     I1MACH( 1) = THE STANDARD INPUT UNIT.
C     I1MACH( 2) = THE STANDARD OUTPUT UNIT.
C     I1MACH( 3) = THE STANDARD PUNCH UNIT.
C     I1MACH( 4) = THE STANDARD ERROR MESSAGE UNIT.
C     I1MACH( 5) = THE NUMBER OF BITS PER INTEGER STORAGE UNIT.
C     I1MACH( 6) = THE NUMBER OF CHARACTERS PER INTEGER STORAGE UNIT.
C     I1MACH( 7) = A, THE BASE (RADIX) FOR INTEGERS.
C     I1MACH( 8) = S, THE NUMBER OF BASE-A DIGITS.
C     I1MACH( 9) = A**S - 1, THE LARGEST MAGNITUDE.
C     I1MACH(10) = B, THE BASE FOR FLOATING-POINT (16 FOR IBM HEX).
C     I1MACH(11) = T, THE NUMBER OF BASE-B DIGITS (SINGLE PRECISION).
C     I1MACH(12) = EMIN, THE SMALLEST EXPONENT (SINGLE PRECISION).
C     I1MACH(13) = EMAX, THE LARGEST EXPONENT (SINGLE PRECISION).
C     I1MACH(14) = T, THE NUMBER OF BASE-B DIGITS (DOUBLE PRECISION).
C     I1MACH(15) = EMIN, THE SMALLEST EXPONENT (DOUBLE PRECISION).
C     I1MACH(16) = EMAX, THE LARGEST EXPONENT (DOUBLE PRECISION).
C
      IF (I .LT. 1 .OR. I .GT. 16) GO TO 10
      I1MACH = IMACH(I)
      RETURN
C
   10 CONTINUE
      WRITE(6,100) I
  100 FORMAT(' I1MACH - I OUT OF BOUNDS:',I10)
      I1MACH = 0
      RETURN
      END
